In [1]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 1)) (2.3.1)
Requirement already satisfied: pandas in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: scikit-learn in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 3)) (1.7.0)
Requirement already satisfied: openai in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 4)) (1.95.1)
Requirement already satisfied: groq in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 5)) (0.30.0)
Requirement already satisfied: seaborn in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 6)) (0.13.2)
Requirement already satisfied: dotenv in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 7)) (0.9.9)
Requirement already satisfied: matplotlib in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from -r requirements.txt (line 8)) (3.10.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (2.11.7)
Requirement already satisfied: sniffio in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from openai->-r requirements.txt (line 4)) (4.14.1)
Requirement already satisfied: idna>=2.8 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from anyio<5,>=3.5.0->openai->-r requirements.txt (line 4)) (3.10)
Requirement already satisfied: certifi in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from httpx<1,>=0.23.0->openai->-r requirements.txt (line 4)) (2025.7.14)
Requirement already satisfied: httpcore==1.* in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from httpx<1,>=0.23.0->openai->-r requirements.txt (line 4)) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->-r requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 4)) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: python-dotenv in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from dotenv->-r requirements.txt (line 7)) (1.1.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from matplotlib->-r requirements.txt (line 8)) (3.2.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\bprmls\lib\site-packages (from tqdm>4->openai->-r requirements.txt (line 4)) (0.4.6)

### 1.Import Dependencies

In [2]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

### 2. Basic Processing

In [3]:
df = pd.read_csv('EDA/data/processed/FeautureEncoding_Applied.csv')
df.head(5)

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,101348.88,1,1,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,112542.58,0,1,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,113931.57,1,0,True,False,False,True,False
3,38.91,1,0.00,2,0,0,93826.63,0,2,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,79084.10,0,4,False,False,True,True,False

### 3. Important Concepts

#### 2.1.1 What is Normalization?

Normalization is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1. It is also known as Min-Max scaling.

#### 2.1.2 What is Standardization?

Standardization is another scaling technique where the values are centered around the mean with aunit standard deviation. This means that the mean of the attribute becomes zero and the resultant distibution has a unit standard deviation

| Condition | Min-Max Scaling | Standardization (Z-score) |
|-----------|----------------|------------------------|
| Data has a known, fixed range | ✅ Yes | ❌ Not ideal |
| Data contains outliers | ❌ Sensitive to outliers | ✅ More robust to outliers |
| Data is normally distributed | ❌ Not necessary | ✅ Preferred |
| Data is not normally distributed (e.g., skewed) | ✅ If shape needs to be preserved | ✅ Often works well after log-transform |
| Model is distance-based (KNN, SVM) | ✅ Recommended | ✅ Also acceptable |
| Model is neural network | ✅ Strongly recommended | ❌ May slow training |
| Model is linear or uses regularization | ❌ Not ideal | ✅ Helps with convergence |
| Input features need bounded values (0–1) | ✅ Required | ❌ Not bounded |
| Applying PCA or LDA | ❌ May distort variance | ✅ Required (centering needed) |
| Want to preserve original distribution shape | ✅ Maintains feature shape | ✅ Maintains shape but centers data |
| Working with tree-based models | ❌ Not needed | ❌ Not needed |

In [4]:
Columns_need_to_be_scaled = ['Age', 'Tenure', 'Balance', 'EstimatedSalary']

for col in Columns_need_to_be_scaled:
 scalar = StandardScaler()
 #scalar = MinMaxScaler()
df[col] = scalar.fit_transform(df[col].values.reshape(10000, 1))

df

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,0.021886,1,1,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,0.216534,0,1,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,0.240687,1,0,True,False,False,True,False
3,38.91,1,0.00,2,0,0,-0.108918,0,2,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,-0.365276,0,4,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,39.00,5,0.00,2,1,0,-0.066419,0,3,True,False,False,False,True
9996,35.00,10,57369.61,1,1,1,0.027988,0,0,True,False,False,False,True
9997,36.00,7,0.00,1,0,1,-1.008643,1,2,True,False,False,True,False
9998,42.00,3,75075.31,2,1,0,-0.125231,1,3,False,True,False,False,True
9999,28.00,4,130142.79,1,1,0,-1.076370,0,3,True,False,False,True,False

In [6]:
df.to_csv(
                  'EDA/data/processed/ChurnModelling_Final.csv',
                  index= False
                )